base_url = "https://xpltt.vercel.app/"
title = "Welcome"
description = "A modern blog with glassmorphism design and aurora animations"

compile_sass = true
build_search_index = true
minify_html = true

taxonomies = [
    { name = "tags", feed = true },
    { name = "authors", feed = true },
    { name = "categories", feed = true }
]

[markdown]
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

highlighting = { theme = "github-dark" }

[extra]
home = "back"

background_image = "https://raw.githubusercontent.com/Jahamars/zola-prism/refs/heads/main/static/bg.jpg"

show_toc = true

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "about", link = "/about" },
    { text = "github", link = "https://github.com/jahamars/zola-prism" },
    { text = "authors", link = "/authors" },
    { text = "tags", link = "/tags" },
    { text = "Categories", link = "/categories" }
]

sam_bottom_menu = true

show_word_count = true
show_reading_time = true

date_format = "%b %d, %Y"

comments = true

[extra.giscus]
enabled = true
repo = "Jahamars/zola-prism"
repo_id = "R_kgDORAdmkg"
category = "Announcements"
category_id = "DIC_kwDORAdmks4C120r"
mapping = "pathname"
strict = "0"
reactions_enabled = "1"
emit_metadata = "0"
input_position = "bottom"
theme = "catppuccin_frappe"
lang = "en"

[extra.sam_footer]
text = "Built using Zola & Prism theme"

[extra.author]
name = "Jahongir Ahmadaliev"
email = ""
url = "https://jahongir.ru"

[extra.features]
copy_code_button = true
reading_progress_bar = true
smooth_scroll = true
