name = "Prism"
description = "A modern Zola theme featuring glassmorphism design"
license = "AGPL-3.0"
homepage = "https://github.com/jahamars/zola-prism"
demo = "https://xpltt.vercel.app/"

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_bottom_menu = true

[author]
name = "Jahongir Ahmadaliev"
homepage = "https://jahongir.ru"
